# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'
inhibit_all_warnings!

target 'BusNS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for BusNS
  pod "Texture", :inhibit_warnings => true
  pod 'Alamofire', :inhibit_warnings => true
  pod 'Firebase/Analytics', :inhibit_warnings => true
  pod 'Firebase/Crashlytics', :inhibit_warnings => true
  pod 'MBProgressHUD', :inhibit_warnings => true
  pod 'MaterialComponents/Snackbar', :inhibit_warnings => true
  
  target 'BusNSTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
