# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
inhibit_all_warnings!

target 'BusNS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BusNS
	pod "Texture", :inhibit_warnings => true
	pod 'Alamofire', '~> 5.0', :inhibit_warnings => true

  target 'BusNSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
